<?xml version="1.0" encoding="utf-8"?><Database Name="Example" Class="BoardDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=Example;User ID=origin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ExampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.board" Member="board">
    <Type Name="board">
      <Column Name="bno" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="writer" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="regdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>